#! /bin/bash

dt=`date +%Y-%m-%d_%H%M%S`
db=rd

function dump () {
    collection=$1
    fn=$dt
    fn+=__$collection.json
    echo DUMP "$collection" to "$fn"
    mongoexport -d $db -c $collection -o "$fn"
}

dump user
dump agent
